# Generated by Django 5.2.7 on 2026-01-06 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('member_no', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_at_death', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('crematory', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deceased/photos/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('church', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='families.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family', 'Family'), ('wedding', 'Wedding'), ('achievement', 'Achievement')], max_length=20)),
                ('image', models.ImageField(upload_to='family/gallery/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address_if_different', models.TextField(blank=True, null=True)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('place_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
