# Generated by Django 5.2.7 on 2026-01-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_add_parents_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='photo',
        ),
        migrations.AddField(
            model_name='familymember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband_or_wife', to='families.familymember'),
        ),
    ]
