# Generated by Django 6.0.2 on 2026-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0021_alter_relationship_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
