# Generated by Django 6.0.2 on 2026-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0023_relationship_is_inferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
