# Generated by Django 6.0.2 on 2026-03-31 05:21

from django.db import migrations
from collections import defaultdict, deque

def int_to_roman(num):
    """Convert integer to Roman numeral."""
    val = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
    syms = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
    roman_num = ''
    i = 0
    while num > 0:
        for _ in range(num // val[i]):
            roman_num += syms[i]
            num -= val[i]
        i += 1
    return roman_num

def populate_member_ids(apps, schema_editor):
    """Populate member_id field with generation info and spouse indicators."""
    FamilyMember = apps.get_model('families', 'FamilyMember')
    Relationship = apps.get_model('families', 'Relationship')
    
    # Get all members
    members = list(FamilyMember.objects.all())
    if not members:
        return
    
    # Build parent-child relationships
    parent_children = defaultdict(set)
    child_parents = defaultdict(set)
    
    for member in members:
        for parent in member.parents.all():
            parent_children[parent.id].add(member.id)
            child_parents[member.id].add(parent.id)
    
    # Calculate generation depth for each member using BFS
    # Generation 0 = those with no parents
    # Generation N = max(parent generation) + 1
    generation_map = {}
    queue = deque()
    
    # Start with root members (no parents)
    for member in members:
        if not child_parents.get(member.id):
            generation_map[member.id] = 0
            queue.append(member.id)
    
    # BFS to calculate generation depths
    while queue:
        member_id = queue.popleft()
        current_gen = generation_map[member_id]
        
        # Children are in next generation
        for child_id in parent_children.get(member_id, []):
            if child_id not in generation_map:
                generation_map[child_id] = current_gen + 1
                queue.append(child_id)
            else:
                # Child might have multiple parents, take max generation
                generation_map[child_id] = max(generation_map[child_id], current_gen + 1)
    
    # Members without parents and without children (orphans) assigned to generation 0
    for member in members:
        if member.id not in generation_map:
            generation_map[member.id] = 0
    
    # Get all spouse relationships
    spouse_pairs = set()
    for rel in Relationship.objects.filter(relation_type='Spouse'):
        # Canonical order: (min_id, max_id)
        pair = (min(rel.from_member_id, rel.to_member_id), max(rel.from_member_id, rel.to_member_id))
        spouse_pairs.add(pair)
    
    # Create map of which members are spouses (for W suffixing)
    # Store as: {female_member_id: male_member_id} for applying W suffix
    spouse_map = {}  # member_id -> spouse_id_base
    for a_id, b_id in spouse_pairs:
        member_a = next((m for m in members if m.id == a_id), None)
        member_b = next((m for m in members if m.id == b_id), None)
        if member_a and member_b:
            # Apply W suffix to female spouse
            if member_a.gender == 'F':
                spouse_map[a_id] = b_id
            elif member_b.gender == 'F':
                spouse_map[b_id] = a_id
    
    # Group members by generation and sort by name within each generation
    gen_groups = defaultdict(list)
    for member in members:
        gen = generation_map.get(member.id, 0)
        gen_groups[gen].append(member)
    
    # Assign member_ids
    for gen in sorted(gen_groups.keys()):
        # Sort by name for consistent numbering
        members_in_gen = sorted(gen_groups[gen], key=lambda m: m.name)
        roman_gen = int_to_roman(gen + 1)  # Start from I, not 0
        
        for idx, member in enumerate(members_in_gen, start=1):
            base_member_id = f"{roman_gen} {idx}"
            
            # If this member is a female spouse, add W suffix
            if member.id in spouse_map:
                member.member_id = f"{base_member_id}W"
            else:
                member.member_id = base_member_id
            
            member.save()

def reverse_populate_member_ids(apps, schema_editor):
    """Remove member_id values."""
    FamilyMember = apps.get_model('families', 'FamilyMember')
    FamilyMember.objects.all().update(member_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('families', '0024_familymember_member_id'),
    ]

    operations = [
        migrations.RunPython(populate_member_ids, reverse_populate_member_ids),
    ]
