# Generated by Django 6.0.2 on 2026-03-31 05:21

from django.db import migrations
from collections import defaultdict

def clean_duplicate_spouses(apps, schema_editor):
    """Remove bidirectional spouse relationships, keeping only canonical order (min_id, max_id)."""
    Relationship = apps.get_model('families', 'Relationship')
    
    # Find all SPOUSE relationships
    spouse_rels = Relationship.objects.filter(relation_type='Spouse')
    
    # Track pairs we've seen to identify reverses
    seen_pairs = set()
    duplicates_to_delete = []
    
    for rel in spouse_rels:
        a, b = rel.from_member_id, rel.to_member_id
        # Canonical pair (always min, max)
        canonical = (min(a, b), max(a, b))
        
        if canonical in seen_pairs:
            # This is a duplicate (reverse) of one we've already seen
            duplicates_to_delete.append(rel.id)
        else:
            seen_pairs.add(canonical)
    
    # Delete all duplicate relationships
    if duplicates_to_delete:
        Relationship.objects.filter(id__in=duplicates_to_delete).delete()

def reverse_clean_duplicate_spouses(apps, schema_editor):
    """Reverse is not needed - we're only removing duplicates."""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('families', '0025_populate_member_ids'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_spouses, reverse_clean_duplicate_spouses),
    ]
