# Generated by Django 6.0.2 on 2026-04-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0028_familymember_name_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_label', models.CharField(default='2026-28', max_length=20)),
                ('category', models.CharField(choices=[('office_bearer', 'Office Bearer'), ('committee_member', 'Committee Member')], max_length=20)),
                ('role_title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('house_name', models.CharField(blank=True, max_length=200, null=True)),
                ('member_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee/photos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_records', to='families.familymember')),
            ],
            options={
                'ordering': ['term_label', 'category', 'display_order', 'name'],
            },
        ),
    ]
