# Generated by Django 6.0.2 on 2026-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0029_familycommitteemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='wedding_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
    ]
