# Generated by Django 6.0.2 on 2026-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0031_family_address_family_email_family_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
