# Generated by Django 5.2.7 on 2026-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0032_familymember_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
