# Generated by Django 5.2.7 on 2026-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0033_familymember_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='branch',
            field=models.CharField(blank=True, choices=[('Thazhe branch', 'Kollamparampil Thazhe branch'), ('Karottu branch', 'Kollamparampil Karottu branch'), ('Tharavadu branch', 'Kollamparampil Tharavadu branch'), ('Kulathamackal branch', 'Kollamparampil Kulathamackal branch'), ('Akkare branch', 'Kollamparampil Akkare branch'), ('Mulekkunnu branch', 'Kollamparampil Mulekkunnu branch'), ('Kuttickal branch', 'Kollamparampil Kuttickal branch')], max_length=50, null=True),
        ),
    ]
