# Generated by Django 5.2.7 on 2026-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. SPONSOR', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('purpose', models.TextField(help_text='e.g. Help us cover basic maintenance costs.')),
                ('upi_id', models.CharField(help_text='e.g. merchant@upi', max_length=255)),
                ('payee_name', models.CharField(help_text='e.g. ABC Store', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this option')),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears on the frontend')),
            ],
            options={
                'verbose_name': 'Donation Option',
                'verbose_name_plural': 'Donation Options',
                'ordering': ['order', 'amount'],
            },
        ),
    ]
