# Generated by Django 6.0.2 on 2026-04-21 08:46

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_add_can_manage_all_to_communityrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('pic', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='pic',
            field=image_cropping.fields.ImageCropField(upload_to='committee/'),
        ),
    ]
