# Generated by Django 6.0.2 on 2026-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_committee_cropping_alter_committee_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
