# Generated by Django 5.2.7 on 2026-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text="Required if type is 'event'", null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
